 $(document).ready(function(){
  $("#comment-in").click(function(){
      $("#comment-out").slideToggle();
      $("#comment-in").slideToggle();
  });
  $("#load-more").click(function(){
    $("#section-6").slideToggle();
    $("#section-7").slideToggle();
    $("#load-more").slideToggle();
});
});